"""add recommendation logs and feedback

Revision ID: 53ea5aefc2b6
Revises: 4192ba3cd80d
Create Date: 2025-09-13 20:19:18.132480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53ea5aefc2b6'
down_revision: Union[str, Sequence[str], None] = '4192ba3cd80d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.Column('useful', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['show_id'], ['shows.show_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'show_id', name='uq_feedback_user_show')
    )
    op.create_index(op.f('ix_recommendation_feedback_show_id'), 'recommendation_feedback', ['show_id'], unique=False)
    op.create_index(op.f('ix_recommendation_feedback_user_id'), 'recommendation_feedback', ['user_id'], unique=False)
    op.create_table('recommendation_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('components_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['show_id'], ['shows.show_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_log_show_id'), 'recommendation_log', ['show_id'], unique=False)
    op.create_index(op.f('ix_recommendation_log_user_id'), 'recommendation_log', ['user_id'], unique=False)
    # Fresh DBs may never have had the legacy `user_ratings` table.
    # Use IF EXISTS so this migration can run safely everywhere.
    op.execute("DROP TABLE IF EXISTS user_ratings CASCADE")

    ##op.drop_index(op.f('ix_users_username'), table_name='users')
    ##op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    ##op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    ##op.drop_constraint(None, 'users', type_='unique')
    ##op.drop_index(op.f('ix_users_id'), table_name='users')
    ##op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('user_ratings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tmdb_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('watched_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('seasons_completed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], name=op.f('user_ratings_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_ratings_pkey')),
    sa.UniqueConstraint('user_id', 'tmdb_id', name=op.f('uq_user_rating'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_user_ratings_user_id'), 'user_ratings', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_ratings_tmdb_id'), 'user_ratings', ['tmdb_id'], unique=False)
    op.drop_index(op.f('ix_recommendation_log_user_id'), table_name='recommendation_log')
    op.drop_index(op.f('ix_recommendation_log_show_id'), table_name='recommendation_log')
    op.drop_table('recommendation_log')
    op.drop_index(op.f('ix_recommendation_feedback_user_id'), table_name='recommendation_feedback')
    op.drop_index(op.f('ix_recommendation_feedback_show_id'), table_name='recommendation_feedback')
    op.drop_table('recommendation_feedback')
    # ### end Alembic commands ###
