"""create auth_users

Revision ID: f3110f124c61
Revises: 25d0e576b13c
Create Date: 2025-10-08 20:39:09.069949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3110f124c61'
down_revision: Union[str, Sequence[str], None] = '25d0e576b13c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_rating_tmdb_id', table_name='user_rating')
    op.drop_index('ix_user_rating_user_id', table_name='user_rating')
    op.drop_table('user_rating')
    op.drop_index('ix_favorites_tmdb_tmdb_id', table_name='favorites_tmdb')
    op.drop_index('ix_favorites_tmdb_user_id', table_name='favorites_tmdb')
    op.drop_table('favorites_tmdb')
    op.drop_index('ix_recommendation_feedback_show_id', table_name='recommendation_feedback')
    op.drop_index('ix_recommendation_feedback_user_id', table_name='recommendation_feedback')
    op.drop_table('recommendation_feedback')
    op.drop_index('ix_recommendation_log_show_id', table_name='recommendation_log')
    op.drop_index('ix_recommendation_log_user_id', table_name='recommendation_log')
    op.drop_table('recommendation_log')
    op.drop_index('ix_rec_feedback_id', table_name='rec_feedback')
    op.drop_index('ix_rec_feedback_show_id', table_name='rec_feedback')
    op.drop_index('ix_rec_feedback_user_id', table_name='rec_feedback')
    op.drop_table('rec_feedback')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_table('users')
    op.add_column('auth_users', sa.Column('username', sa.String(length=255), nullable=True))
    op.alter_column('auth_users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint('uq_auth_users_email', 'auth_users', ['email'])
    op.add_column('not_interested', sa.Column('tmdb_id', sa.Integer(), nullable=False))
    op.drop_index('ix_not_interested_show_id', table_name='not_interested')
    op.drop_constraint('uq_not_interested_user_show', 'not_interested', type_='unique')
    op.create_index(op.f('ix_not_interested_tmdb_id'), 'not_interested', ['tmdb_id'], unique=False)
    op.create_unique_constraint('uq_not_interested_user_tmdb', 'not_interested', ['user_id', 'tmdb_id'])
    op.drop_constraint('not_interested_show_id_fkey', 'not_interested', type_='foreignkey')
    op.drop_constraint('not_interested_user_id_fkey', 'not_interested', type_='foreignkey')
    op.create_foreign_key(None, 'not_interested', 'auth_users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('not_interested', 'reason')
    op.drop_column('not_interested', 'show_id')
    op.alter_column('reddit_posts', 'reddit_id',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=32),
               nullable=True)
    op.alter_column('reddit_posts', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('reddit_posts', 'url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               nullable=False)
    op.alter_column('reddit_posts', 'score',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('reddit_posts', 'subreddit',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=200),
               nullable=True)
    op.drop_index('ix_reddit_posts_subreddit', table_name='reddit_posts')
    op.create_index(op.f('ix_reddit_posts_created_utc'), 'reddit_posts', ['created_utc'], unique=False)
    op.create_index(op.f('ix_reddit_posts_show_id'), 'reddit_posts', ['show_id'], unique=False)
    op.drop_column('reddit_posts', 'num_comments')
    op.alter_column('shows', 'title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=300),
               existing_nullable=False)
    op.alter_column('shows', 'poster_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.drop_constraint('shows_external_id_key', 'shows', type_='unique')
    op.create_index(op.f('ix_shows_external_id'), 'shows', ['external_id'], unique=False)
    op.drop_column('shows', 'cast')
    op.drop_column('shows', 'created_at')
    op.drop_column('shows', 'genres')
    op.drop_column('shows', 'platforms')
    op.drop_column('shows', 'language')
    op.drop_column('shows', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('shows', sa.Column('language', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('shows', sa.Column('platforms', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('shows', sa.Column('genres', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('shows', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('shows', sa.Column('cast', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_shows_external_id'), table_name='shows')
    op.create_unique_constraint('shows_external_id_key', 'shows', ['external_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('shows', 'poster_url',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('shows', 'title',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.add_column('reddit_posts', sa.Column('num_comments', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_reddit_posts_show_id'), table_name='reddit_posts')
    op.drop_index(op.f('ix_reddit_posts_created_utc'), table_name='reddit_posts')
    op.create_index('ix_reddit_posts_subreddit', 'reddit_posts', ['subreddit'], unique=False)
    op.alter_column('reddit_posts', 'subreddit',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('reddit_posts', 'score',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('reddit_posts', 'url',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('reddit_posts', 'title',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('reddit_posts', 'reddit_id',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=20),
               nullable=False)
    op.add_column('not_interested', sa.Column('show_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('not_interested', sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'not_interested', type_='foreignkey')
    op.create_foreign_key('not_interested_user_id_fkey', 'not_interested', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('not_interested_show_id_fkey', 'not_interested', 'shows', ['show_id'], ['show_id'], ondelete='CASCADE')
    op.drop_constraint('uq_not_interested_user_tmdb', 'not_interested', type_='unique')
    op.drop_index(op.f('ix_not_interested_tmdb_id'), table_name='not_interested')
    op.create_unique_constraint('uq_not_interested_user_show', 'not_interested', ['user_id', 'show_id'], postgresql_nulls_not_distinct=False)
    op.create_index('ix_not_interested_show_id', 'not_interested', ['show_id'], unique=False)
    op.drop_column('not_interested', 'tmdb_id')
    op.drop_constraint('uq_auth_users_email', 'auth_users', type_='unique')
    op.alter_column('auth_users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('auth_users', 'username')
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('username', name='users_username_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_table('rec_feedback',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('show_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('useful', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='rec_feedback_pkey')
    )
    op.create_index('ix_rec_feedback_user_id', 'rec_feedback', ['user_id'], unique=False)
    op.create_index('ix_rec_feedback_show_id', 'rec_feedback', ['show_id'], unique=False)
    op.create_index('ix_rec_feedback_id', 'rec_feedback', ['id'], unique=False)
    op.create_table('recommendation_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('show_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('components_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['show_id'], ['shows.show_id'], name='recommendation_log_show_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='recommendation_log_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='recommendation_log_pkey')
    )
    op.create_index('ix_recommendation_log_user_id', 'recommendation_log', ['user_id'], unique=False)
    op.create_index('ix_recommendation_log_show_id', 'recommendation_log', ['show_id'], unique=False)
    op.create_table('recommendation_feedback',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('show_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('useful', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['show_id'], ['shows.show_id'], name='recommendation_feedback_show_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='recommendation_feedback_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='recommendation_feedback_pkey'),
    sa.UniqueConstraint('user_id', 'show_id', name='uq_feedback_user_show', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('ix_recommendation_feedback_user_id', 'recommendation_feedback', ['user_id'], unique=False)
    op.create_index('ix_recommendation_feedback_show_id', 'recommendation_feedback', ['show_id'], unique=False)
    op.create_table('favorites_tmdb',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tmdb_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='favorites_tmdb_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='favorites_tmdb_pkey'),
    sa.UniqueConstraint('user_id', 'tmdb_id', name='uq_user_tmdb', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('ix_favorites_tmdb_user_id', 'favorites_tmdb', ['user_id'], unique=False)
    op.create_index('ix_favorites_tmdb_tmdb_id', 'favorites_tmdb', ['tmdb_id'], unique=False)
    op.create_table('user_rating',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tmdb_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('watched_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('seasons_completed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_rating_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_rating_pkey'),
    sa.UniqueConstraint('user_id', 'tmdb_id', name='uq_rating_user_show', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('ix_user_rating_user_id', 'user_rating', ['user_id'], unique=False)
    op.create_index('ix_user_rating_tmdb_id', 'user_rating', ['tmdb_id'], unique=False)
    # ### end Alembic commands ###
